cache:
  CACHE_TYPE: simple
jwt:
  SECRET: secret
  EXPIRE_HOURS: 24
app:
  SALT: bar
  ENV: dev
  SECRET: \xe3\x1d4zl<O\x01WR\xad0\x98}n|.\xc5\x08(\xaf\xea-\x11
  HOST: 127.0.0.1
  PORT: 5000
db:
  # MYSQL:mysql+pymysql://root:2020012377@mysql:3306/thss
  MYSQL: sqlite:///dev.db